### ISSUE TITLE
BOOK NOW PAGE

### ISSUE THREAD

**Issue by SaddamDeveloper** [SaddamDeveloper/aborhut#2]
Book Now page isn't there.

**Comment by Narayanaash** [comment]
Tell me what are the fields required, i will design that tomorrow

**Comment by SaddamDeveloper** [comment]
in this project is there any cart or not ask sir about it.
if it has cart the
i need cart page
and then checkout page with address and then proceed to pay
after that thank you page

**Comment by Narayanaash** [comment]
It is up to you, I will design whatever you say…

**Comment by Narayanaash** [comment]
If there is any doubt, then you can ask Pranab, he has complete information
about this project.

**Comment by SaddamDeveloper** [comment]
Great Work Aash!!!
